### ISSUE TITLE
Deceptive site warning

### ISSUE THREAD

**Issue by nachiketkanore** [Akshat111111/india-flix#1]
![image](https://github.com/Akshat111111/india-flix/assets/44920607/dde51359-e47e-4a9f-9e21-b6c0fa952d4b)

**Comment by Akshat111111** [comment]
It's not dangerous,the warning is due to vercel deployment

**Comment by Akshat111111** [comment]
Now u can check brother and let me know if everything is fine

**Comment by nachiketkanore** [comment]
It's working fine now!
Closing this issue!
